package com.crisy.mybatis.dao;


import com.crisy.mybatis.pojo.Sc;

public interface ScMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc
     *
     * @mbggenerated
     */
    int insert(Sc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc
     *
     * @mbggenerated
     */
    int insertSelective(Sc record);
}