package com.crisy.mybatis.pojo;

public class Sc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc.sno
     *
     * @mbggenerated
     */
    private Integer sno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc.cno
     *
     * @mbggenerated
     */
    private Integer cno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc.score
     *
     * @mbggenerated
     */
    private Integer score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc.sno
     *
     * @return the value of sc.sno
     *
     * @mbggenerated
     */
    public Integer getSno() {
        return sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc.sno
     *
     * @param sno the value for sc.sno
     *
     * @mbggenerated
     */
    public void setSno(Integer sno) {
        this.sno = sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc.cno
     *
     * @return the value of sc.cno
     *
     * @mbggenerated
     */
    public Integer getCno() {
        return cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc.cno
     *
     * @param cno the value for sc.cno
     *
     * @mbggenerated
     */
    public void setCno(Integer cno) {
        this.cno = cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc.score
     *
     * @return the value of sc.score
     *
     * @mbggenerated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc.score
     *
     * @param score the value for sc.score
     *
     * @mbggenerated
     */
    public void setScore(Integer score) {
        this.score = score;
    }
}